#!/usr/bin/env python3
"""Generic protocol/summary generator for any PDF workspace."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from services import local_llm  # noqa: E402
from services.generic_retrieval import GenericRetrievalBackend  # noqa: E402


PROMPT = """You are a research assistant. Summarize the evidence to answer the question.
Question: {question}

Evidence:
{evidence}

Instructions:
- Provide a multi-paragraph response with inline references like [1], [2].
- Include a final section called 'Sources' listing each PDF file referenced.
"""


def format_evidence(results):
    lines = []
    for idx, item in enumerate(results, start=1):
        meta = item.get("metadata", {})
        source = meta.get("pdf_file") or "unknown.pdf"
        lines.append(f"[{idx}] ({source})\n{item['text']}")
    return "\n\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workspace", type=Path, help="Workspace root generated by generic_run_pipeline.")
    parser.add_argument("question", help="Question or task to answer.")
    parser.add_argument("--top-k", type=int, default=8)
    args = parser.parse_args()

    backend = GenericRetrievalBackend(args.workspace)
    results = backend.search(args.question, top_k=args.top_k)
    if not results:
        print("No evidence found.")
        return
    prompt = PROMPT.format(question=args.question, evidence=format_evidence(results))
    answer = local_llm.generate(prompt)
    print(answer)


if __name__ == "__main__":
    main()
